

services:
  frontend:
    image: robertcieplinski/mypage:latest
    pull_policy: always
    container_name: mypage-frontend
    env_file:
      - .env.frontend
    ports:
      - "127.0.0.1:3000:3000"
    restart: unless-stopped
    networks:
      - nginx-setup_internal-net

networks:
  nginx-setup_internal-net:
    external: true
    name: nginx-setup_internal-net
